<?php

return [
    'default_preset' => 'emerald',

    'presets' => [
        'emerald' => [
            'label' => 'Emerald',
            'description' => 'Hijau emerald — tampilan default CarinaSmartCup',
            'css' => [
                '--brand-50' => '#ecfdf5',
                '--brand-100' => '#d1fae5',
                '--brand-200' => '#a7f3d0',
                '--brand-500' => '#10b981',
                '--brand-600' => '#059669',
                '--brand-700' => '#047857',
                '--brand-800' => '#065f46',
                '--brand-900' => '#064e3b',
                '--brand-fg' => '#ffffff',
                '--page-bg' => '#fafaf9',
            ],
        ],
        'ocean' => [
            'label' => 'Ocean',
            'description' => 'Biru laut dengan aksen cyan',
            'css' => [
                '--brand-50' => '#ecfeff',
                '--brand-100' => '#cffafe',
                '--brand-200' => '#a5f3fc',
                '--brand-500' => '#06b6d4',
                '--brand-600' => '#0891b2',
                '--brand-700' => '#0e7490',
                '--brand-800' => '#155e75',
                '--brand-900' => '#164e63',
                '--brand-fg' => '#ffffff',
                '--page-bg' => '#f8fafc',
            ],
        ],
        'forest' => [
            'label' => 'Forest',
            'description' => 'Hijau tua dengan latar cream lembut',
            'css' => [
                '--brand-50' => '#f3f6f1',
                '--brand-100' => '#e4ebdf',
                '--brand-200' => '#c9d7bf',
                '--brand-500' => '#5f7d4f',
                '--brand-600' => '#4a643d',
                '--brand-700' => '#3b5031',
                '--brand-800' => '#2f4028',
                '--brand-900' => '#24321f',
                '--brand-fg' => '#ffffff',
                '--page-bg' => '#f7f4ee',
            ],
        ],
        'slate' => [
            'label' => 'Slate',
            'description' => 'Abu gelap dengan aksen lime',
            'css' => [
                '--brand-50' => '#f8fafc',
                '--brand-100' => '#f1f5f9',
                '--brand-200' => '#e2e8f0',
                '--brand-500' => '#84cc16',
                '--brand-600' => '#65a30d',
                '--brand-700' => '#4d7c0f',
                '--brand-800' => '#334155',
                '--brand-900' => '#0f172a',
                '--brand-fg' => '#ffffff',
                '--page-bg' => '#f8fafc',
            ],
        ],
        'navy' => [
            'label' => 'Navy',
            'description' => 'Navy dengan aksen emas lembut',
            'css' => [
                '--brand-50' => '#f8fafc',
                '--brand-100' => '#eef2ff',
                '--brand-200' => '#dbe3f5',
                '--brand-500' => '#c4a35a',
                '--brand-600' => '#1e3a5f',
                '--brand-700' => '#172b46',
                '--brand-800' => '#122238',
                '--brand-900' => '#0b1624',
                '--brand-fg' => '#ffffff',
                '--page-bg' => '#f5f7fb',
            ],
        ],
        'rose' => [
            'label' => 'Rose',
            'description' => 'Rose gelap dengan nuansa stone',
            'css' => [
                '--brand-50' => '#fff1f2',
                '--brand-100' => '#ffe4e6',
                '--brand-200' => '#fecdd3',
                '--brand-500' => '#f43f5e',
                '--brand-600' => '#e11d48',
                '--brand-700' => '#be123c',
                '--brand-800' => '#9f1239',
                '--brand-900' => '#881337',
                '--brand-fg' => '#ffffff',
                '--page-bg' => '#fafaf9',
            ],
        ],
    ],
];
